export interface  LoanApplication {
    message: string;
    loanApplicationId: number,
    applicationNo: number,
    memberId: number,
    componentId: number,
    purposeId : number,
    memberName  : string,
    memberCode  : string,
    officeName  : string,
    applicationAmount: number,
    approvedAmount: number,
    applicationDate: Date,
    proposedBy: number,
    firstGuarantorMemberId: number,
    firstGuarantorName  : string,
    firstGuarantorContactNo : string,
    firstGuarantorRelation: string,
    firstGuarantorRemark: string,
    secendGuarantorMemberId  : number,
    secendGuarantorName : string,
    secendGuarantorContactNo : string,
    secendGuarantorRelation : string,
    secendGuarantorRemark : string,
    applicationStatus: string,
    approvedLevel : number,
    checkedBy : number,
    checkedDate : Date,
    firstApprovedBy : number,
    firstApproveddate : Date,
    secendApprovedBy: number,
    secendApproveddate : Date,
    thirdApprovedBy : number,
    thirdApproveddate : Date,
    fourthApprovedBy : number,
    fourthApproveddate : Date,
}